Public Module ceCatalogo
    Public idArticulo
    Public Descripcion
    Public idCategoria
    Public Categoria
    Public idSubCategoria
    Public SubCategoria
    Public idMarca
    Public Marca
    Public idUnidad
    Public Unidad
    Public localizacion
    Public StockMin
    Public StockMax
    Public factor
    Public precioCompra
    Public preCompraProm
    Public margen1
    Public margen2
    Public margen3
    Public margen4
    Public margen5
    Public precio1
    Public precio2
    Public precio3
    Public precio4
    Public precio5
    Public mayoreo1
    Public mayoreo2
    Public mayoreo3
    Public Mayoreo4
    Public Mayoreo5
    Public Activo
    Public Frecuente
    Public FechaUltMov
    Public Servicio
    Public Imagen
    Public RutaImagen
End Module
