Public Module ceClientes
    Public idCliente
    Public Nombre
    Public IdTpIdentificacion
    Public TpIdentificacion
    Public NroIdentificacion
    Public Ubigeo_Distrito
    Public Departamento
    Public Provincia
    Public Distrito
    Public Direccion
    Public Telefonos
    Public email
    Public WhatsApp
    Public NombreContacto
    Public TelefonoContacto
    Public idZona
    Public Zona
End Module
